### ISSUE TITLE
UI freezes

### ISSUE THREAD

**Issue by AsranV** [SpikeHimself/XPortal#60] opened 2023-08-07 05:21 UTC
**Describe the bug**
I can log in on the server with my character, but when I go to the portal and interact with it, the UI gets freezed on the middle of the screen and I can only close the game to fix it. There's no other way to get rid of the UI. I can't choose the destination or change the name of the portal.

**To Reproduce**
Login in and using TP

**LogOutput file(s)**
I don't know how to find this and I have to go work. I'll look for it later. 

**Version**
1.2.13 on r2modman

**Environment**
Choose from the following options where you are experiencing the problem (leave only the ones you know about):
* Multiplayer Host (my game is the server)

**Other mods**
BeastsOfBurden
BepinExPack
BetterDiving
Blacksmith_tools
BoneAppetit
ChaosArmor
Dualwield
EpicValheimadditions
ExtendedPlayerInventory
Fantasy_Armoury
Fantasy_Creatures
FarmGrid
Farmyard_Animals
Fruit_Trees
InfiniteTorches
Jotunn
Judes_Equipment
MountUP
OdinArchitect
OdinFoodBarrels
PopVillages
RRRCore
RRRMonsters
RRRNpcs
Sages_Vault
Spawn_That
SpearFishing
TrashItems
Valharvest
ValheimArmory
ValheimRAFTpdated
Wildlife

**Priority**
Estimate how important this problem is. Choose Medium if you don't know.
* High (XPortal does not work at all anymore)

**Additional information**
This seems to be the error I get when trying to use the portal:

[Error : Unity Log] TypeLoadException: Could not resolve type with token 01000091 (from typeref, class/assembly UIGamePad, assembly_guiutils, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null)

Stack trace:

XPortal.UI.PortalConfigurationPanel.InitialiseUI () (at <e556ccad14a3493fbc4b90983a56316e>:0)

XPortal.UI.PortalConfigurationPanel.ConfigurePortal (XPortal.KnownPortal portal) (at <e556ccad14a3493fbc4b90983a56316e>:0)

XPortal.XPortal.OnPortalRequestText (ZDOID portalId) (at <e556ccad14a3493fbc4b90983a56316e>:0)

XPortal.Patches.TextInput_RequestText.Prefix (TextReceiver sign) (at <e556ccad14a3493fbc4b90983a56316e>:0)

(wrapper dynamic-method) TextInput.DMD<TextInput::RequestText>(TextInput,TextReceiver,string,int)

TeleportWorld.Interact (Humanoid human, System.Boolean hold, System.Boolean alt) (at <478cefef01544173a8b5828694dc7192>:0)

Player.Interact (UnityEngine.GameObject go, System.Boolean hold, System.Boolean alt) (at <478cefef01544173a8b5828694dc7192>:0)

(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

**Comment by SunnyDaze21** [comment] 2023-08-22 20:23
I'm having the same issue as above.

**Comment by tdrury** [comment] 2023-08-24 18:30
This curious. I just created https://github.com/SpikeHimself/XPortal/issues/61 because I didn't think this issue was the same because you logged it 3 weeks ago and XPortal was working fine for me just a couple days ago before the Hilda update. But they appear to be the same issue. Were you running the Hilda beta perhaps?

**Comment by amazingornaldo** [comment] 2023-08-24 18:57
I am getting this as well post Hilda update. I run a server on my VMWare server VM and have had no issues with this mod before this latest Valheim patch. And to add, my dialog window was pink. But I had to close Valheim via the program manager as I could not click on quit as the XPortal dialog would not go away.

**Comment by SunnyDaze21** [comment] 2023-08-24 23:34
> 

I was not running the beta.

**Comment by SpikeHimself** [comment] 2023-08-26 11:46
Sorry for the delay everyone, life has been busy over here. I have just released v1.2.14 which should address this issue. If it has not, or you find other issues, please let me know. I will leave this issue open for now.

**Comment by SpikeHimself** [comment] 2023-08-27 13:44
Confirmed fixed by v1.2.14

**Closed by SpikeHimself** 2023-08-27 13:44 UTC
Labels: bug
