### ISSUE TITLE
Fetching Portals Info

### ISSUE THREAD

**Issue by Postyon** [SpikeHimself/XPortal#9] opened 2023-02-06 00:08 UTC
new portals says "Fetching portals Info" and can't be destroyed

**Comment by SpikeHimself** [comment] 2023-02-06 08:52
Thanks for reporting!

Are you playing single player or do you join a server? Is the server also running the latest version?

Could you turn on debug logging and send me your BepInEx output logs? If you run a server seperately, then please also provide the logs of the server.

See also #10

**Comment by SpikeHimself** [comment] 2023-02-06 13:04
Closing as duplicate of #10

**Closed by SpikeHimself** 2023-02-06 13:04 UTC
Labels: duplicate, incomplete
