### ISSUE TITLE
Can not enter anything in UI and configure the portal

### ISSUE THREAD

**Issue by wjuszczyk** [SpikeHimself/XPortal#93] opened 2024-01-22 14:30 UTC
**Describe the bug**
When trying to configure portal UI window is visible but can not type anything.

**To Reproduce**
Configure portal.

**Expected behaviour**
UI is usable and configuration possible.

**LogOutput file(s)**
[Error  : Unity Log] MissingFieldException: Field not found: System.Collections.Generic.Dictionary`2<TMPro.TMP_Text, string> .Localization.textMeshStrings Due to: Could not find field in class
Stack trace:
XPortal.UI.PortalConfigurationPanel.AddGamepadHint (UnityEngine.GameObject go, System.String buttonName, UnityEngine.KeyCode keyCode) (at <ce0741c05f1e4a36b8ba25321392e7fa>:0)
XPortal.UI.PortalConfigurationPanel.InitialiseUI () (at <ce0741c05f1e4a36b8ba25321392e7fa>:0)
XPortal.UI.PortalConfigurationPanel.ConfigurePortal (XPortal.KnownPortal portal) (at <ce0741c05f1e4a36b8ba25321392e7fa>:0)
XPortal.XPortal.OnPortalRequestText (ZDOID portalId) (at <ce0741c05f1e4a36b8ba25321392e7fa>:0)
XPortal.Patches.TextInput_RequestText.Prefix (TextReceiver sign) (at <ce0741c05f1e4a36b8ba25321392e7fa>:0)
(wrapper dynamic-method) TextInput.DMD<TextInput::RequestText>(TextInput,TextReceiver,string,int)
(wrapper dynamic-method) TeleportWorld.DMD<TeleportWorld::Interact>(TeleportWorld,Humanoid,bool,bool)
(wrapper dynamic-method) Player.DMD<Player::Interact>(Player,UnityEngine.GameObject,bool,bool)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

and 

[Error  : Unity Log] NullReferenceException: Object reference not set to an instance of an object
Stack trace:
XPortal.UI.PortalConfigurationPanel.ConfigurePortal (XPortal.KnownPortal portal) (at <ce0741c05f1e4a36b8ba25321392e7fa>:0)
XPortal.XPortal.OnPortalRequestText (ZDOID portalId) (at <ce0741c05f1e4a36b8ba25321392e7fa>:0)
XPortal.Patches.TextInput_RequestText.Prefix (TextReceiver sign) (at <ce0741c05f1e4a36b8ba25321392e7fa>:0)
(wrapper dynamic-method) TextInput.DMD<TextInput::RequestText>(TextInput,TextReceiver,string,int)
(wrapper dynamic-method) TeleportWorld.DMD<TeleportWorld::Interact>(TeleportWorld,Humanoid,bool,bool)
(wrapper dynamic-method) Player.DMD<Player::Interact>(Player,UnityEngine.GameObject,bool,bool)
(wrapper dynamic-method) Player.DMD<Player::Update>(Player)

**Version**
1.2.20

**Environment**
* Singleplayer

**Priority**
* Medium (XPortal kind of still works, but it's not pleasant to use)

**Comment by SpikeHimself** [comment] 2024-01-28 11:59
Hi @wjuszczyk, thank you for reporting this issue.

Can you please attach your log file so I can investigate your issue?

**Comment by SpikeHimself** [comment] 2024-04-30 13:59
Closing this issue because I can not reproduce it, and I did not receive feedback. If you're still having this problem please let me know.

**Closed by SpikeHimself** 2024-04-30 13:59 UTC
Labels: bug
