### ISSUE TITLE
Advanced Portals not retaining 'name' and 'destination' info after logging out

### ISSUE THREAD

**Issue by kmGaijin** [SpikeHimself/XPortal#70] opened 2023-09-12 23:36 UTC
**Describe the bug**
* With RandyKnaps Advanced portals, only the vanilla wood portals retain name and destination info after logging out.
* All vanilla wood portals are fine, but any other portal loses all info upon logout.

**To Reproduce**
* Create an Ancient, Obsidian or BlackMarble portal.
* Save a name and destination info.
* Save and logout of game.

**Expected behavior**
* When I log back in the name and destination info is saved to the portals

**LogOutput file(s)**
* [LogOutput.log](https://github.com/SpikeHimself/XPortal/files/12591593/LogOutput.log)

**Version**
* 1.2.17

**Priority**
* Low

**Additional information**

From looking at the logs, the portals that show up in game with no 'name' or 'destination' actually look like they have info stored for them.

This portal is actually the BlackMarble Portal named 'gxplains'
https://i.imgur.com/hpFAHaF.jpeg

This is the list when interacting with that portal.
None of the advanced portals are listed, only the plain vanilla wood ones.
https://i.imgur.com/utgWCM7.png

**Comment by SpikeHimself** [comment] 2023-09-12 23:57
Hi @kmGaijin, thanks for reporting.

The cause of this is that along with the Hildir's Request update, Valheim changed the functionality that is used to retrieve all portals. This also created issue #59.

I think I can make a work-around for this, but it will be a big change. Ideally this should be fixed not by XPortal but by Advanced Portals. That mod needs to make sure that the Advanced Portals are returned by `ZDOMan.instance.GetPortals()`

**Comment by SpikeHimself** [comment] 2023-09-12 23:59
It seems someone else has already run into this issue, see https://github.com/RandyKnapp/ValheimMods/issues/617

**Comment by kmGaijin** [comment] 2023-09-13 00:15
Ah, thanks Spike.

**Comment by SpikeHimself** [comment] 2023-09-25 23:27
Hi @kmGaijin, this issue has been solved by Advanced Portals, see: https://github.com/RandyKnapp/ValheimMods/issues/617#issuecomment-1734519824

**Closed by SpikeHimself** 2023-09-25 23:27 UTC
Labels: compatibility
