### ISSUE TITLE
XPortal crashes on dedicated server with Valheim Plus installed

### ISSUE THREAD

**Issue by BooMaLiCiOuS** [SpikeHimself/XPortal#29] opened 2023-03-09 23:32 UTC
**Describe the bug**
- I have installed Xportal to a dedicated server running Valheim Plus only (Server side). Since installing (March 8th) I have had to fly around the map to "remap" the portals. I am unsure as to why, but the portal names are reverting back to nothing which means there is nothing to also select for a destination.

**To Reproduce** 
- Install Valheim Plus and XPortal on dedicated server
- Run the server
- A player joins the server
-  XPortal (on the server) will now receive a sync request, this is where the error occurs (in `XPortal.KnownPortal.GetColour()`).

**LogOutput file(s)**
- ~~[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/10937134/LogOutput.log)~~
- [LogOutput.log](https://github.com/SpikeHimself/XPortal/files/10937490/LogOutput.log)

**Version** 
- 1.2.6

**Environment** 
- Dedicated Server

**Other mods** 
- Jotunn 2.10.4
- Valheim Plus 0.9.9.11

**Priority** 
- Medium

---

 Edits by @SpikeHimself :

### Updated summary (2023-03-28)

- As soon as a player joins, the server is trying to build a list of all portals so that it can send that to the player. This immediately goes wrong, because the server is failing to retrieve the portal colour:

```
[Info   :XPortal.RPC] Received sync request from `206028287` because: Achilliez (206028287) has joined the game
[Info   : Unity Log] 03/09/2023 17:07:21: Exception in ZRpc::HandlePackage: System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. 
---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. 
---> System.NullReferenceException: Object reference not set to an instance of an object
  at XPortal.KnownPortal.GetColour (UnityEngine.GameObject prefab) 
  at XPortal.KnownPortal.GetPortalColour (ZDOID portalId) 
  at XPortal.KnownPortal..ctor (ZDOID id) 
  at XPortal.KnownPortalsManager.UpdateFromZDOList (System.Collections.Generic.List`1[T] zdoList)
  at XPortal.XPortal.ForceLocalPortalUpdate (System.Collections.Generic.List`1[T] allPortals)
  at XPortal.XPortal.ProcessSyncRequest (System.String reason) 
  at XPortal.RPC.RPC_SyncRequest (System.Int64 sender, System.String reason) 
```

In v1.2.6 this error could occur if the portal prefab does not have child GameObject `_target_found_red/Point light` or that child does not have a `Light` component:

https://github.com/SpikeHimself/XPortal/blob/0af97be809fea73263e416d24760c071644a4a43/XPortal/KnownPortal.cs#L24-L28

Newer versions of XPortal have improved logging so that we can determine the precise cause, but this was not yet tested by this issue's author. 

**We do know that removing ValheimPlus resolves the issue.** Therefore this is a compatibility issue.

---

### Steps to take to help with testing

* Download the latest [Debug release](https://github.com/SpikeHimself/XPortal/releases) of XPortal
* [Enable debug logging](https://github.com/SpikeHimself/resources/wiki/BepInEx:-Enable-debug-logging) in your BepInEx config
* Install Valheim Plus and the latest Debug release of XPortal on a dedicated server
* Run the server with a world that already has portals (or create one first)
* Join the server
* Share the server's `LogOutput.log`

**Comment by SpikeHimself** [comment] 2023-03-09 23:35
Hi, thanks for reporting!

Please could you double check the log? It seems to cut off early.

**Comment by BooMaLiCiOuS** [comment] 2023-03-10 00:46
Sorry about that. Here you go.
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/10937490/LogOutput.log)

**Comment by SpikeHimself** [comment] 2023-03-10 01:04
Thanks!

There are 3 things I can see that are going wrong:

1. When XPortal loads you're getting a warning from HarmonyX. I'm not sure why this is happening, but I don't think this is related to the problem you are experiencing. I've had this message reported from one other player a few days ago, but I didn't get enough feedback to diagnose it properly. 

    - Could you turn debug logging on and send me a fresh log file?

2. As soon as a player joins, the server is trying to build a list of all portals so that it can send that to the player. This immediately goes wrong, because the server is failing to retrieve the portal colour (this is a new feature in the latest version and I am beginning to suspect that this doesn't work on dedicated servers). 

    - This error is the root cause of your issue, as at this point XPortal "crashes" and does not continue with updating portals. Any future attempts will fail for the same reason.

3. Immediately after this, you are getting an error from Valheim Plus. I can't say anything about that though, because I am not familiar with how Valheim Plus works.

Just to confirm, this was the logfile of your dedicated server, right? Could you also send me the log file of your client session (i.e. your own game)?

**Comment by BooMaLiCiOuS** [comment] 2023-03-10 01:15
I have enabled debug mode per your reply and restarted the server. Here is the updated log from the dedicated server. 
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/10937582/LogOutput.log)

Here is a log of my personal, but I was not on when the portals lost their names. 
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/10937588/LogOutput.log)

**Comment by SpikeHimself** [comment] 2023-03-10 01:28
> I have enabled debug mode per your reply and restarted the server. Here is the updated log from the dedicated server.

There are no errors in this new logfile. Did the problem not occur this time?


In my previous comment I hinted at the possibility that dedicated servers are simply not capable of getting the colour from a portal, but this turns out to be incorrect: I've just run a test on my own dedicated server, and everything is working fine for me.

Could you try disabling Valheim Plus and see if the problem still occurs?

**Comment by BooMaLiCiOuS** [comment] 2023-03-10 01:48
Here is the latest log file. When I logged in, the portals were reset back to no name again.
[LogOutput.log](https://github.com/SpikeHimself/XPortal/files/10937718/LogOutput.log)

Here is with Valheim Plus disabled.
[LogOutput_WithVP_Disabled.log](https://github.com/SpikeHimself/XPortal/files/10937729/LogOutput_WithVP_Disabled.log)

**Comment by SpikeHimself** [comment] 2023-03-10 01:51
> Here is with Valheim Plus disabled.

Two issues here:

1. Nobody connected so the error didn't happen
2. Valheim Plus is still enabled:
    [Info   :   BepInEx] Loading [Valheim Plus 0.9.9.11]

**Comment by BooMaLiCiOuS** [comment] 2023-03-10 02:36
So I disabled valheim plus and connected to the server. The portals do have their tags as you stated they should.

**Comment by SpikeHimself** [comment] 2023-03-10 08:21
Right, so something in Valheim Plus is causing a conflict. Now we have to figure out what :)

I've never used Valheim Plus but I think it has sections you can turn on and off? Is that something you could try out?

In the meantime I'll try to have a look at Valheim Plus' code to see if I can find anything.

**Comment by BooMaLiCiOuS** [comment] 2023-03-10 20:41
I have not. :(

**Comment by SpikeHimself** [comment] 2023-03-10 21:54
Does that mean you haven't had time or you were not able to discover anything? In case of the latter, what have you tried? I want to fix this issue but I don't want to install VH+ on my  machine, so you're going to have to be my eyes and ears for this one.

In the meantime I did make some changes which may or may not help. I have attached a debug build to this comment. The .zip contains 3 files, they go where XPortal.dll sits - replacing it and adding 2 new files. 

[XPortal-v1.2.6-debug-issue-29.zip](https://github.com/SpikeHimself/XPortal/files/10946430/XPortal-v1.2.6-debug-issue-29.zip)

Could you try to reproduce the problem with this debug version?

**Comment by SpikeHimself** [comment] 2023-03-14 21:02
That file is now outdated. I have released 1.2.7 just a few moments ago.

Please let me know when you have time to do further testing, so I can create a new debug file for you, with the latest changes.

**Comment by SpikeHimself** [comment] 2023-03-27 22:14
Leaving this open because clearly an issue exists, but without further information I cannot work on it. If someone sees this and wants to dive in, give me a shout!

**Comment by SpikeHimself** [comment] 2023-06-13 18:48
This issue is dated and nobody else brought it up, I am closing this as assumed-solved.

**Closed by SpikeHimself** 2023-06-13 18:48 UTC
Labels: help wanted, incomplete, compatibility, hotfix
